import React from "react";
import Head from "next/dist/shared/lib/head";
import RegisterPage from "../component/Register/Register";
const Register = () => {
  return (
    <>
      <Head>
        <title>Register Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossorigin="anonymous"
        />
      </Head>
      <main>
        <RegisterPage />
      </main>
    </>
  );
};

export default Register;
